project:
  type: website
  output-dir: docs

website:
  title: "Kansas State workshop, December 2024"
  sidebar:
    background: primary
    collapse-level: 1
    contents:
      - text: "Bees Ft Riley ğŸ"
        href: cassidy/lathrom.qmd
      - section: "Sandhill birds ğŸ¦"
        contents:
          - rachel/rusten.qmd
          - rachel/rusten_grids.qmd
          - rachel/modelsel_compare.qmd
      - text: "Mourning doves ğŸ•Šï¸"
        href: natalie/pegg.qmd
      - about.qmd

format:
  html:
    theme: 
      - yeti
      - eric_theme.scss
    css: styles.css
    toc: true



